import { AIModel, AIProvider } from '@/types';

export const AI_PROVIDERS: Record<AIProvider, { name: string; logo: string; website: string; icon: string }> = {
  openrouter: {
    name: 'OpenRouter',
    logo: '/logos/openrouter.svg',
    website: 'https://openrouter.ai',
    icon: '🔀',
  },
  google: {
    name: 'Google AI',
    logo: '/logos/google.svg',
    website: 'https://ai.google.dev',
    icon: '✨',
  },
  anthropic: {
    name: 'Anthropic',
    logo: '/logos/anthropic.svg',
    website: 'https://anthropic.com',
    icon: '🧠',
  },
  openai: {
    name: 'OpenAI',
    logo: '/logos/openai.svg',
    website: 'https://openai.com',
    icon: '🤖',
  },
  mistral: {
    name: 'Mistral AI',
    logo: '/logos/mistral.svg',
    website: 'https://mistral.ai',
    icon: '🌬️',
  },
  groq: {
    name: 'Groq',
    logo: '/logos/groq.svg',
    website: 'https://groq.com',
    icon: '⚡',
  },
  together: {
    name: 'Together AI',
    logo: '/logos/together.svg',
    website: 'https://together.ai',
    icon: '🤝',
  },
  perplexity: {
    name: 'Perplexity',
    logo: '/logos/perplexity.svg',
    website: 'https://perplexity.ai',
    icon: '🔍',
  },
};

export const AI_MODELS: AIModel[] = [
  // OpenRouter Models (Free Tier)
  {
    id: 'openrouter/meta-llama/llama-3.2-3b-instruct:free',
    name: 'Llama 3.2 3B (Free)',
    provider: 'openrouter',
    description: 'Fast and efficient Llama model for general tasks',
    contextWindow: 131072,
    maxOutputTokens: 4096,
    inputPricing: 0,
    outputPricing: 0,
    capabilities: { chat: true, vision: false, functionCalling: false, streaming: true, codeExecution: false, webSearch: false },
    isFree: true,
    isAvailable: true,
  },
  {
    id: 'openrouter/google/gemma-2-9b-it:free',
    name: 'Gemma 2 9B (Free)',
    provider: 'openrouter',
    description: 'Google Gemma 2 with 9B parameters',
    contextWindow: 8192,
    maxOutputTokens: 4096,
    inputPricing: 0,
    outputPricing: 0,
    capabilities: { chat: true, vision: false, functionCalling: false, streaming: true, codeExecution: false, webSearch: false },
    isFree: true,
    isAvailable: true,
  },
  {
    id: 'openrouter/mistralai/mistral-7b-instruct:free',
    name: 'Mistral 7B (Free)',
    provider: 'openrouter',
    description: 'Efficient Mistral model for various tasks',
    contextWindow: 32768,
    maxOutputTokens: 4096,
    inputPricing: 0,
    outputPricing: 0,
    capabilities: { chat: true, vision: false, functionCalling: false, streaming: true, codeExecution: false, webSearch: false },
    isFree: true,
    isAvailable: true,
  },
  {
    id: 'openrouter/qwen/qwen-2-7b-instruct:free',
    name: 'Qwen 2 7B (Free)',
    provider: 'openrouter',
    description: 'Alibaba Qwen 2 model with strong multilingual support',
    contextWindow: 32768,
    maxOutputTokens: 4096,
    inputPricing: 0,
    outputPricing: 0,
    capabilities: { chat: true, vision: false, functionCalling: false, streaming: true, codeExecution: false, webSearch: false },
    isFree: true,
    isAvailable: true,
  },

  // Google Gemini Models
  {
    id: 'google/gemini-1.5-flash',
    name: 'Gemini 1.5 Flash',
    provider: 'google',
    description: 'Fast and versatile multimodal model',
    contextWindow: 1000000,
    maxOutputTokens: 8192,
    inputPricing: 0.075,
    outputPricing: 0.3,
    capabilities: { chat: true, vision: true, functionCalling: true, streaming: true, codeExecution: true, webSearch: false },
    isFree: true,
    isAvailable: true,
  },
  {
    id: 'google/gemini-1.5-pro',
    name: 'Gemini 1.5 Pro',
    provider: 'google',
    description: 'Most capable Gemini model for complex tasks',
    contextWindow: 2000000,
    maxOutputTokens: 8192,
    inputPricing: 1.25,
    outputPricing: 5,
    capabilities: { chat: true, vision: true, functionCalling: true, streaming: true, codeExecution: true, webSearch: false },
    isFree: true,
    isAvailable: true,
  },
  {
    id: 'google/gemini-2.0-flash-exp',
    name: 'Gemini 2.0 Flash (Experimental)',
    provider: 'google',
    description: 'Latest experimental Gemini 2.0 with enhanced capabilities',
    contextWindow: 1000000,
    maxOutputTokens: 8192,
    inputPricing: 0,
    outputPricing: 0,
    capabilities: { chat: true, vision: true, functionCalling: true, streaming: true, codeExecution: true, webSearch: true },
    isFree: true,
    isAvailable: true,
  },

  // Anthropic Claude Models
  {
    id: 'anthropic/claude-3-haiku-20240307',
    name: 'Claude 3 Haiku',
    provider: 'anthropic',
    description: 'Fast and cost-effective for simple tasks',
    contextWindow: 200000,
    maxOutputTokens: 4096,
    inputPricing: 0.25,
    outputPricing: 1.25,
    capabilities: { chat: true, vision: true, functionCalling: true, streaming: true, codeExecution: false, webSearch: false },
    isFree: false,
    isAvailable: true,
  },
  {
    id: 'anthropic/claude-3.5-sonnet-20241022',
    name: 'Claude 3.5 Sonnet',
    provider: 'anthropic',
    description: 'Best balance of speed and intelligence',
    contextWindow: 200000,
    maxOutputTokens: 8192,
    inputPricing: 3,
    outputPricing: 15,
    capabilities: { chat: true, vision: true, functionCalling: true, streaming: true, codeExecution: true, webSearch: false },
    isFree: false,
    isAvailable: true,
  },
  {
    id: 'anthropic/claude-3-opus-20240229',
    name: 'Claude 3 Opus',
    provider: 'anthropic',
    description: 'Most capable Claude for complex reasoning',
    contextWindow: 200000,
    maxOutputTokens: 4096,
    inputPricing: 15,
    outputPricing: 75,
    capabilities: { chat: true, vision: true, functionCalling: true, streaming: true, codeExecution: false, webSearch: false },
    isFree: false,
    isAvailable: true,
  },

  // OpenAI Models (via OpenRouter)
  {
    id: 'openrouter/openai/gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'openai',
    description: 'Affordable and capable GPT-4 variant',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputPricing: 0.15,
    outputPricing: 0.6,
    capabilities: { chat: true, vision: true, functionCalling: true, streaming: true, codeExecution: false, webSearch: false },
    isFree: false,
    isAvailable: true,
  },
  {
    id: 'openrouter/openai/gpt-4o',
    name: 'GPT-4o',
    provider: 'openai',
    description: 'Flagship multimodal GPT-4 model',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputPricing: 2.5,
    outputPricing: 10,
    capabilities: { chat: true, vision: true, functionCalling: true, streaming: true, codeExecution: false, webSearch: false },
    isFree: false,
    isAvailable: true,
  },

  // Groq Models (Fast Inference)
  {
    id: 'groq/llama-3.3-70b-versatile',
    name: 'Llama 3.3 70B (Groq)',
    provider: 'groq',
    description: 'Ultra-fast inference with Groq hardware',
    contextWindow: 128000,
    maxOutputTokens: 32768,
    inputPricing: 0.59,
    outputPricing: 0.79,
    capabilities: { chat: true, vision: false, functionCalling: true, streaming: true, codeExecution: false, webSearch: false },
    isFree: false,
    isAvailable: true,
  },
  {
    id: 'groq/mixtral-8x7b-32768',
    name: 'Mixtral 8x7B (Groq)',
    provider: 'groq',
    description: 'Fast Mixtral inference on Groq',
    contextWindow: 32768,
    maxOutputTokens: 4096,
    inputPricing: 0.24,
    outputPricing: 0.24,
    capabilities: { chat: true, vision: false, functionCalling: false, streaming: true, codeExecution: false, webSearch: false },
    isFree: false,
    isAvailable: true,
  },
];

export const DEFAULT_CONVERSATION_SETTINGS = {
  temperature: 0.7,
  maxTokens: 4096,
  topP: 1,
  frequencyPenalty: 0,
  presencePenalty: 0,
  stopSequences: [],
  streamResponse: true,
};

export const DEFAULT_USER_PREFERENCES = {
  theme: 'system' as const,
  defaultModel: 'google/gemini-1.5-flash',
  defaultTemperature: 0.7,
  defaultMaxTokens: 4096,
  sendOnEnter: true,
  showTimestamps: true,
  compactMode: false,
  codeTheme: 'github-dark',
  language: 'en',
  notifications: {
    enabled: true,
    sound: false,
    desktop: false,
  },
};

export const PROJECT_COLORS = [
  '#ef4444', '#f97316', '#f59e0b', '#eab308', '#84cc16',
  '#22c55e', '#10b981', '#14b8a6', '#06b6d4', '#0ea5e9',
  '#3b82f6', '#6366f1', '#8b5cf6', '#a855f7', '#d946ef',
  '#ec4899', '#f43f5e',
];

export const PROJECT_ICONS = [
  '💬', '🚀', '💡', '📝', '🎯', '⚡', '🔥', '✨',
  '🎨', '🛠️', '📊', '🔬', '🎮', '📚', '🌟', '💻',
];

export const KEYBOARD_SHORTCUTS = {
  newChat: { key: 'n', modifiers: ['ctrl'] },
  newProject: { key: 'p', modifiers: ['ctrl', 'shift'] },
  toggleSidebar: { key: 'b', modifiers: ['ctrl'] },
  toggleSettings: { key: ',', modifiers: ['ctrl'] },
  search: { key: 'k', modifiers: ['ctrl'] },
  focusInput: { key: '/', modifiers: [] },
  regenerate: { key: 'r', modifiers: ['ctrl', 'shift'] },
  copyLastResponse: { key: 'c', modifiers: ['ctrl', 'shift'] },
};
